<?php
class Booki_PageNames{
	const CART = 0;
	const USER_DASHBOARD = 1;
	const PAYPAL_HANDLER = 2;
	const PAYPAL_CONFIRMATION_HANDLER = 3;
	const BOOKING_VIEW = 4;
	const PAYPAL_CANCEL_HANDLER = 5;
	CONST HISTORY_PAGE = 6;
	CONST STATS_PAGE = 7;
}
?>