<?php
require_once  dirname(__FILE__) . '/../infrastructure/utils/Helper.php';
require_once  dirname(__FILE__) . '/../infrastructure/ui/lists/ImageList.php';
class Booki_Create{
	public $currency;
	public $currencySymbol;
	public $decimalPoint;
	public $thousandsSep;
	public $imageList;
	public $imageListContent;
	public function __construct(){
		$localeInfo = Booki_Helper::getLocaleInfo();
		$locale = $localeInfo['locale'];
		
		$this->currency = $localeInfo['currency'];
		$this->currencySymbol = $localeInfo['currencySymbol'];
		
		$this->decimalPoint = $locale['decimal_point'];
		$this->thousandsSep = $locale['thousands_sep'];
		$this->imageList = new Booki_ImageList();
		$this->imageList->prepare_items();
		ob_start();
		$this->imageList->display();
		$this->imageListContent = ob_get_contents();
		ob_end_clean();
	}
}

$_Booki_Create = new Booki_Create();
?>
<div class="booki">
	<?php require dirname(__FILE__) .'/partials/restrictedmodewarning.php' ?>
	<div class="booki col-lg-12">
		<div class="booki-callout booki-callout-info">
			<h4><?php echo __('Create, edit and delete projects', 'booki')?></h4>
			<p><?php echo __('The basis for any bookings. It all takes place here. A project is how you define a unique booking.', 'booki') ?> </p>
		</div>
		<script type="text/javascript">
			jQuery(document).ready(function($) {
				Booki.localization = {
					"currency": "<?php echo $_Booki_Create->currency?>"
					, "currencySymbol": "<?php echo $_Booki_Create->currencySymbol?>"
					, "decimalPoint": "<?php echo $_Booki_Create->decimalPoint?>"
					, "thousandsSep": "<?php echo $_Booki_Create->thousandsSep?>"
				};
				Booki.resx = {
					"BASE_PROGRESS_MODAL_HEADING": "<?php echo __('Request in progress...', 'booki') ?>"
					, "PROJECT_TAB_PROJECT_NAME_LABEL": "<?php echo __('Project', 'booki')?>"
					, "PROJECT_TAB_CREATE_NEW_LABEL": "<?php echo __('Create new', 'booki') ?>"
					, "PROJECT_TAB_SHORT_CODE_LABEL": "<?php echo __('Short Code', 'booki') ?>"
					, "PROJECT_TAB_DUPLICATE_PROJECT_LABEL": "<?php echo __('Duplicate project name', 'booki') ?>"
					, "PROJECT_TAB_DUPLICATE_PROJECT": "<?php echo __('Duplicate project', 'booki') ?>"
					, "PROJECT_TAB_PROJECT_DUPLICATE_LABEL": "<?php echo __('Create', 'booki') ?>"
					, "PROJECT_TAB_PROJECT_DUPLICATE_HEADING": "<?php echo __('Duplicate project name', 'booki') ?>"
					, "PROJECT_TAB_PROJECT_DUPLICATE_INFO": "<?php echo __('Supply a name for your duplicate project and hit create. This will create a duplicate of all the settings of the current project. This is especially helpful when you want to create a list of separate bookings, based off the current booking. The new duplicated project will contain everything from project settings, to form fields, booking calendar values and optionals. Cascading lists will be copied over too but the relationships will be reset. That means you will have to re-establish the relationships for cascading lists again.', 'booki') ?>"
					, "PROJECT_TAB_NAME_LABEL": "<?php echo __('Name', 'booki') ?>"
					, "PROJECT_TAB_BOOKING_MODE_HEADING": "<?php echo __('Attention: Booking mode', 'booki') ?>"
					, "PROJECT_TAB_STATUS_HEADING": "<?php echo __('Project status', 'booki') ?>"
					, "PROJECT_TAB_STATUS_INFO": "<?php echo __('A projects status can be \"running\", this means it will still serve bookings if there are available days OR the status can be \"stopped\", which means bookings won\'t be allowed regardless of bookings availability.', 'booki') ?>"
					, "PROJECT_TAB_STATUS_RUNNING": "<?php echo __('Running', 'booki') ?>"
					, "PROJECT_TAB_STATUS_STOPPED": "<?php echo __('Stopped', 'booki') ?>"
					, "PROJECT_TAB_BOOKING_MODE_INFO": "<?php echo __('Reservation mode allows multiple users to book the same day and time slot intervals. Appointment mode on the other hand allows only one time bookings. Once a booking is made, the same day/time combinations won\'t be available for booking again.', 'booki') ?>"
					, "PROJECT_TAB_BOOKING_MODE_LABEL": "<?php echo __('Booking mode', 'booki') ?>"
					, "PROJECT_TAB_RESERVATION": "<?php echo __('Reservation', 'booki') ?>"
					, "PROJECT_TAB_APPOINTMENT": "<?php echo __('Appointment', 'booki') ?>"
					, "PROJECT_TAB_BOOKING_DAYS_LIMIT_HEADING": "<?php echo __('Maximum booking days or time slots', 'booki') ?>"
					, "PROJECT_TAB_BOOKING_DAYS_LIMIT_INFO": "<?php echo __('Provide the maximum number of days or time slots that can be booked in a single booking calendar. A value of 1, the default will not allow multiple selections i.e. only 1 day or time slot can be booked at a time. Note when selecting range calendar, ensure that this value is greater than 1.', 'booki') ?>"
					, "PROJECT_TAB_BOOKING_DAYS_LIMIT_LABEL": "<?php echo __('Maximum booking days or time slots', 'booki') ?>"
					, "PROJECT_TAB_BOOKING_DAYS_MINIMUM_HEADING": "<?php echo __('Minimum booking days or timeslots', 'booki') ?>"
					, "PROJECT_TAB_BOOKING_DAYS_MINIMUM_INFO": "<?php echo __('Provide the minimum number of days or timeslots that must be booked in a single booking calendar. A value of 0, the default means no minimum is applied.', 'booki') ?>"
					, "PROJECT_TAB_BOOKING_DAYS_MINIMUM_LABEL": "<?php echo __('Minimum booking days or timeslots', 'booki') ?>"
					, "PROJECT_TAB_CALENDAR_MODE_INFO": "<?php echo __('The bookings calendar can be either pop up, inline, range or next day checkout. A popup calendar is one where a textbox is used to show the selected date which pops up a calendar when clicked allowing date selection. Inline is when an always visible calendar is used. Range will give you a set of \"From\" and \"To\" popup calendars. Next day checkout gives you a range selector that counts the date diff between now and then instead of adding all days in the range.', 'booki') ?>"
					, "PROJECT_TAB_CALENDAR_MODE_LABEL": "<?php echo __('Calendar mode', 'booki') ?>"
					, "PROJECT_TAB_CALENDAR_MODE_POPUP": "<?php echo __('Popup', 'booki') ?>"
					, "PROJECT_TAB_CALENDAR_MODE_INLINE": "<?php echo __('Inline', 'booki') ?>"
					, "PROJECT_TAB_CALENDAR_MODE_RANGE": "<?php echo __('Range', 'booki') ?>"
					, "PROJECT_TAB_CALENDAR_MODE_NEXT_DAY_CHECKOUT": "<?php echo __('Next day check out', 'booki') ?>"
					, "PROJECT_TAB_TAGGING_HEADING": "<?php echo __('Tagging', 'booki') ?>"
					, "PROJECT_TAB_TAGGING_INFO": "<?php echo __('Tagging allows you to group common projects together. Grouped projects get listed using the booki-list shortcode or widget. Select an existing tag or create a new one to associate to this project.', 'booki') ?>"
					, "PROJECT_TAB_TAG_LABEL": "<?php echo __('Tag', 'booki') ?>"
					, "PROJECT_TAB_DESCRIPTION_TITLE": "<?php echo __('A short description. This will be used along with the preview thumbnail when listing projects using the booki-list shortcode or widget.', 'booki') ?>"
					, "PROJECT_TAB_DESCRIPTION_LABEL": "<?php echo __('Description', 'booki') ?>"
					, "PROJECT_TAB_PREVIEW_IMAGE_TITLE": "<?php echo __('A preview image used when listing projects using the booki-list shortcode or widget.', 'booki') ?>"
					, "PROJECT_TAB_PREVIEW_IMAGE_LABEL": "<?php echo __('Preview image', 'booki') ?>"
					, "PROJECT_TAB_LISTING_SETTINGS": "<?php echo __('Project listing settings', 'booki') ?>"
					, "PROJECT_TAB_CONTROL_LABEL_SETTINGS": "<?php echo __('Booking control label settings', 'booki') ?>"
					, "PROJECT_TAB_OPTIONALS_BOOKING_MODE_HEADING": "<?php echo __('Optional Lists and Optional Cascading Lists Booking Mode', 'booki') ?>"
					, "PROJECT_TAB_OPTIONALS_BOOKING_MODE_INFO": "<?php echo __('Optional Lists and Optional Cascading Lists  can apply to a single booking. Note that a single booking can contain multiple days and time slots if your booking allows selecting multiple days and time slots at the same time. Alternatively optionals can apply for each day/time slot selected.', 'booki') ?>"
					, "PROJECT_TAB_GENERAL_SETTINGS": "<?php echo __('General project settings', 'booki') ?>"
					, "PROJECT_TAB_BOOKING_MODE_EACH_BOOKING_LABEL": "<?php echo __('Each booking', 'booki') ?>"
					, "PROJECT_TAB_BOOKING_MODE_EACH_DAY_LABEL": "<?php echo __('Each day or time slot selected', 'booki') ?>"
					, "PROJECT_TAB_OPTIONALS_LISTING_MODE_HEADING": "<?php echo __('Optionals listing mode', 'booki') ?>"
					, "PROJECT_TAB_OPTIONALS_LISTING_MODE_INFO": "<?php echo __('Optional Lists can be presented in a checkbox list which is the default or in a radio button list. If a checkbox list is chosen, you can additionally set the minimum items to be checked, in order to proceed with the booking.', 'booki') ?>"
					, "PROJECT_TAB_CHECKBOX_LIST_LABEL": "<?php echo __('Checkbox List', 'booki') ?>"
					, "PROJECT_TAB_RADIO_BUTTON_LIST": "<?php echo __('RadioButton List', 'booki') ?>"
					, "PROJECT_TAB_OPTIONALS_MINIMUM_SELECTION_LABEL": "<?php echo __('Minimum number of optional selections required', 'booki') ?>"
					, "PROJECT_TAB_ENTER_NEW_TAG_PLACEHOLDER": "<?php echo __('Enter new tag', 'booki') ?>"
					, "PROJECT_TAB_BOOKING_WIZARD_MODE_LABEL": "<?php echo __('Booking wizard mode', 'booki') ?>"
					, "PROJECT_TAB_BOOKING_WIZARD_MODE_TITLE": "<?php echo __('The booking wizard can be split up in two tabs, one containing the booking calendar and optionals, while the other containing the custom form fields. This is the default. Alternatively you can combine it all and display everything linearly, in a top to bottom fashion.', 'booki') ?>"
					, "PROJECT_TAB_TABS_LABEL": "<?php echo __('Tabs', 'booki') ?>"
					, "PROJECT_TAB_LINEAR_LABEL": "<?php echo __('Linear', 'booki') ?>"
					, "PROJECT_TAB_DEFAULT_STEP_TITLE": "<?php echo __('If you set up custom form fields, then this option allows you to decide which form is shown first in the booking wizard.', 'booki') ?>"
					, "PROJECT_TAB_DEFAULT_STEP_LABEL": "<?php echo __('Default step', 'booki') ?>"
					, "PROJECT_TAB_BOOKING_FORM": "<?php echo __('Booking form', 'booki') ?>"
					, "PROJECT_TAB_CUSTOM_FORM_FIELDS": "<?php echo __('Custom form fields', 'booki') ?>"
					, "PROJECT_TAB_BOOKING_TAB_TITLE": "<?php echo __('The label to use for the booking tab in the booking wizard.', 'booki') ?>"
					, "PROJECT_TAB_BOOKING_TAB_LABEL": "<?php echo __('Booking tab caption', 'booki') ?>"
					, "PROJECT_TAB_CUSTOM_FORM_TAB_TITLE": "<?php echo __('The caption to use for the custom form fields tab in the booking wizard.', 'booki') ?>"
					, "PROJECT_TAB_CUSTOM_FORM_TAB_LABEL": "<?php echo __('Custom form fields tab caption', 'booki') ?>"
					, "PROJECT_TAB_AVAILABLE_DAYS_TITLE": "<?php echo __('The label to use for available days field in the booking wizard.', 'booki') ?>"
					, "PROJECT_TAB_AVAILABLE_DAYS_LABEL": "<?php echo __('Available days field label', 'booki') ?>"
					, "PROJECT_TAB_SELECTED_DAYS_TITLE": "<?php echo __('The label to use for the selected days field in the booking wizard.', 'booki') ?>"
					, "PROJECT_TAB_SELECTED_DAYS_LABEL": "<?php echo __('Selected days field label', 'booki') ?>"
					, "PROJECT_TAB_BOOKING_TIME_TITLE": "<?php echo __('The label to use for the booking time dropdown list field in the booking wizard.', 'booki') ?>"
					, "PROJECT_TAB_BOOKING_TIME_LABEL": "<?php echo __('Booking time field label', 'booki') ?>"
					, "PROJECT_TAB_OPTIONAL_ITEM_TITLE": "<?php echo __('The heading to use for the extra billable items checkbox list that allows selection of additional features whose cost add up to the total price in the booking wizard.', 'booki') ?>"
					, "PROJECT_TAB_OPTIONAL_ITEM_LABEL": "<?php echo __('Optional features heading', 'booki') ?>"
					, "PROJECT_TAB_NEXT_BUTTON_TITLE": "<?php echo __('The caption to use in the booking wizards next button.', 'booki') ?>"
					, "PROJECT_TAB_NEXT_BUTTON_LABEL": "<?php echo __('Next button caption', 'booki') ?>"
					, "PROJECT_TAB_PREV_BUTTON_TITLE": "<?php echo __('The caption to use in the booking wizards back button.', 'booki') ?>"
					, "PROJECT_TAB_PREV_BUTTON_LABEL": "<?php echo __('Back button caption', 'booki') ?>"
					, "PROJECT_TAB_ADD_TO_CART_TITLE": "<?php echo __('The caption to use for the create booking button in the booking wizard.', 'booki') ?>"
					, "PROJECT_TAB_ADD_TO_CART_LABEL": "<?php echo __('Create booking button caption', 'booki') ?>"
					, "PROJECT_TAB_FROM_LABEL_TITLE": "<?php echo __('The label to display in the \"From\" range field, when \"Calendar Mode\" is set to \"Range\".', 'booki') ?>"
					, "PROJECT_TAB_FROM_LABEL_LABEL": "<?php echo __('From', 'booki') ?>"
					, "PROJECT_TAB_FROM_LABEL_TITLE": "<?php echo __('The label to display in the \"To\" range field, when \"Calendar Mode\" is set to \"Range\".', 'booki') ?>"
					, "PROJECT_TAB_TO_LABEL_LABEL": "<?php echo __('To', 'booki') ?>"
					, "PROJECT_TAB_HIDE_SELECTED_DAYS_LABEL": "<?php echo __('Hide selected days', 'booki') ?>"
					, "PROJECT_TAB_HIDE_SELECTED_DAYS_TITLE": "<?php echo __('When multiple days selection is enabled, a list of the selected is displayed under the booking calendar. Use this option to toggle the display of that list.', 'booki') ?>"
					, 'PROJECT_TAB_PROCEED_TO_LOGIN_TITLE': "<?php echo __('Sets the label on the button in the booking. Button will show only when user is not logged in when cart system is disabled.', 'booki') ?>"
					, 'PROJECT_TAB_PROCEED_TO_LOGIN_LABEL': "<?php echo __('Proceed to login label', 'booki') ?>"
					, 'PROJECT_TAB_MAKE_BOOKING_TITLE': "<?php echo __('Sets the label on the button used to make the button. This is the button that will display when you disable payments and cart system.', 'booki') ?>"
					, 'PROJECT_TAB_MAKE_BOOKING_LABEL': "<?php echo __('Make booking label', 'booki') ?>"
					, "PROJECT_TAB_BOOKING_LIMIT_LABEL": "<?php echo __('Available seats label', 'booki') ?>"
					, "PROJECT_TAB_BOOKING_LIMIT_TITLE": "<?php echo __('Text used to display the number of available seats left. This option will apply when you set \"Available seats\" and check \"Display counter\", both options available in the booking period tab.', 'booki') ?>"
					, "PROJECT_TAB_BOOKING_LIMIT_LABEL_DEFAULT": "<?php echo __('%d seats left. Hurry!', 'booki') ?>"
					, 'PROJECT_TAB_OPTIONAL_CONTENT': "<?php echo __('Optional HTML content', 'booki') ?>"
					, 'PROJECT_TAB_CONTENT_HEADING': "<?php echo __('Content above and below booking calendar', 'booki') ?>"
					, 'PROJECT_TAB_CONTENT_INFO': "<?php echo __('These settings allow you to insert HTML content above and below the booking calendar.', 'booki') ?>"
					, 'PROJECT_TAB_CONTENT_TOP_LABEL': "<?php echo __('Content above booking calendar', 'booki') ?>"
					, 'PROJECT_TAB_CONTENT_BOTTOM_LABEL': "<?php echo __('Content below booking calendar', 'booki') ?>"
					, "PROJECT_TAB_CREATE_BUTTON_LABEL": "<?php echo __('Create', 'booki') ?>"
					, "PROJECT_TAB_UPDATE_BUTTON_LABEL": "<?php echo __('Update', 'booki') ?>"
					, "PROJECT_TAB_DELETE_BUTTON_LABEL": "<?php echo __('Delete', 'booki') ?>"
					, "PROJECT_TAB_IMAGE_GALLERY_HEADING": "<?php echo __('Image Gallery', 'booki') ?>"
					, "PROJECT_TAB_CLOSE_BUTTON_LABEL": "<?php echo __('Close', 'booki') ?>"
					, 'PROJECT_TAB_DELETE_PROJECT_HEADING': "<?php echo __('Delete Project', 'booki') ?>"
					, 'PROJECT_TAB_DELETE_PROJECT_INFO': "<?php echo __('You are about to delete a project. You will lose any data associated to this project including all bookings made for this project. Are you sure ?', 'booki') ?>"
					, "PROJECT_TAB_LISTING_HEADING_LABEL": "<?php echo __('Find a booking', 'booki')?>"
					, "PROJECT_TAB_LISTING_FROM_LABEL": "<?php echo __('Check-in', 'booki')?>"
					, "PROJECT_TAB_LISTING_TO_LABEL": "<?php echo __('Check-out', 'booki')?>"
					, 'PROJECT_TAB_BOOKING_TAB_LABEL_DEFAULT': "<?php echo __('Booking', 'booki') ?>"
					, 'PROJECT_TAB_CUSTOM_FORM_TAB_LABEL_DEFAULT': "<?php echo __('Details', 'booki') ?>"
					, 'PROJECT_TAB_AVAILABLE_DAYS_LABEL_DEFAULT': "<?php echo __('Available days', 'booki') ?>"
					, 'PROJECT_TAB_SELECTED_DAYS_LABEL_DEFAULT': "<?php echo __('Selected days', 'booki') ?>"
					, 'PROJECT_TAB_BOOKING_TIME_LABEL_DEFAULT': "<?php echo __('Booking time', 'booki') ?>"
					, 'PROJECT_TAB_OPTIONAL_ITEM_LABEL_DEFAULT': "<?php echo __('Optional extras', 'booki') ?>"
					, 'PROJECT_TAB_NEXT_LABEL_DEFAULT': "<?php echo __('Next', 'booki') ?>"
					, 'PROJECT_TAB_PREV_LABEL_DEFAULT': "<?php echo __('Back', 'booki') ?>"
					, 'PROJECT_TAB_ADD_TO_CART_LABEL_DEFAULT': "<?php echo __('Add to cart', 'booki') ?>"
					, 'PROJECT_TAB_FROM_LABEL_DEFAULT': "<?php echo __('From', 'booki') ?>"
					, 'PROJECT_TAB_TO_LABEL_DEFAULT': "<?php echo __('To', 'booki') ?>"
					, 'PROJECT_TAB_PROCEED_TO_LOGIN_LABEL_DEFAULT': "<?php echo __('Proceed', 'booki') ?>"
					, 'PROJECT_TAB_MAKE_BOOKING_LABEL_DEFAULT': "<?php echo __('Make a booking', 'booki') ?>"
					, "PROJECT_TAB_NOTIFY_USER_EMAIL_LIST_LABEL": "<?php echo __('New Booking Notification Recipient(s)', 'booki') ?>"
					, "PROJECT_TAB_NOTIFY_USER_EMAIL_LIST_TITLE": "<?php echo __('Allows you to send new booking notifications to 1 or more people, who will become the intended recipient(s). Multiple recipients may be specified using a comma to separate each email address. i.e. someone@mydomain.com, another@somedomain.com, athird@somewhere.com', 'booki') ?>"
					, 'FORM_BUILDER_TAB_CREATE_NEW_FORM_FIELD_HEADING': "<?php echo __('Create new form field', 'booki') ?>"
					, 'FORM_BUILDER_TAB_CREATE_NEW_FORM_FIELD_INFO': "<?php echo __('Custom form fields will be part of your booking form and allow you to collect additional information and will appear as an integral part of the booking process.', 'booki') ?>"
					, 'FORM_BUILDER_TAB_ELEMENT_TYPE_LABEL': "<?php echo __('Element type', 'booki') ?>"
					, 'FORM_BUILDER_TAB_LABEL_LABEL': "<?php echo __('Label', 'booki') ?>"
					, 'FORM_BUILDER_TAB_VALUE_HEADING': "<?php echo __('Value', 'booki') ?>"
					, 'FORM_BUILDER_TAB_VALUE_INFO': "<?php echo __('The initial value of this field. Setting the same value for multiple radiobutton elements will create a radiobutton group. Note: Only characters, numbers and underscore allowed. ', 'booki') ?>"
					, 'FORM_BUILDER_TAB_VALUE_LABEL': "<?php echo __('Value', 'booki') ?>"
					, 'FORM_BUILDER_TAB_FORM_ELEMENT_URL_LABEL': "<?php echo __('Terms and Conditions Url', 'booki') ?>"
					, 'FORM_BUILDER_TAB_FORM_ELEMENT_URL_INFO': "<?php echo __('Provide the url to your terms and conditions page. If user does not check this field, validation will fail. Combine this with properly worded label set above, eg: Do you agree with our terms and conditions ?', 'booki') ?>"
					, 'FORM_BUILDER_TAB_CONTENT_HEADING': "<?php echo __('Content', 'booki') ?>"
					, 'FORM_BUILDER_TAB_CONTENT_INFO': "<?php echo __('The content for h1 through h6 elements are headings for the sections with which they are associated or just plain text if statictext was your selection in the \"Element type\" field.', 'booki') ?>"
					, 'FORM_BUILDER_TAB_CONTENT_LABEL': "<?php echo __('Content', 'booki') ?>"
					, 'FORM_BUILDER_TAB_CLASSNAME_TITLE': "<?php echo __('Setting a class name allows you to quickly apply css styling to this field. You can also choose one of the following css classes to apply some formatting : [booki-align-left, booki-align-center, booki-align-right, booki-overline, booki-underline, booki-italic, booki-bold, booki-capitalize, booki-uppercase]', 'booki') ?>"
					, 'FORM_BUILDER_TAB_CLASSNAME_LABEL': "<?php echo __('CSS class name', 'booki') ?>"
					, 'FORM_BUILDER_TAB_COLUMN_INDEX_HEADING': "<?php echo __('Column index', 'booki') ?>"
					, 'FORM_BUILDER_TAB_COLUMN_INDEX_INFO': "<?php echo __('Enables multi-column grid. The form element will be placed at the supplied column index. Accepts values 1 - 12. Choose an existing column index from the dropdown list or create a new one. The layout will depend greatly on the screen estate available for the booking form. The smaller the space the more contrived it will appear. Hence we generally recommend single column layouts.', 'booki') ?>"
					, 'FORM_BUILDER_TAB_COLUMN_INDEX_LABEL': "<?php echo __('Column Index', 'booki') ?>"
					, 'FORM_BUILDER_TAB_CREATE_NEW_DEFAULT_SELECTION': "<?php echo __('Create new', 'booki') ?>"
					, 'FORM_BUILDER_TAB_ROW_INDEX_HEADING': "<?php echo __('Row index', 'booki') ?>"
					, 'FORM_BUILDER_TAB_ROW_INDEX_INFO': "<?php echo __('The form element will be placed at the supplied row index. Choose an existing row index from the dropdown list or create a new one.', 'booki') ?>"
					, 'FORM_BUILDER_TAB_ROW_INDEX_LABEL': "<?php echo __('Row Index', 'booki') ?>"
					, 'FORM_BUILDER_TAB_DISPLAY_ONLY_ONCE_HEADING': "<?php echo __('Display only once', 'booki') ?>"
					, 'FORM_BUILDER_TAB_DISPLAY_ONLY_ONCE_INFO': "<?php echo __('When checked, this field is shown only the first time the user is making a booking. If user makes subsequent bookings i.e. adding more days to cart, it won\'t show. Use it to collect one time information.', 'booki') ?>"
					, 'FORM_BUILDER_TAB_DISPLAY_ONLY_ONCE_LABEL': "<?php echo __('Display only once ( on multiple bookings)', 'booki') ?>"
					, 'FORM_BUILDER_TAB_ADD_LINE_SEPARATOR_LABEL': "<?php echo __('Add a line separator after this field', 'booki') ?>"
					, 'FORM_BUILDER_TAB_CHECKED_BY_DEFAULT_LABEL': "<?php echo __('Checked by default', 'booki') ?>"
					, 'FORM_BUILDER_TAB_DATA_SOURCE_HEADING': "<?php echo __('Data source', 'booki') ?>"
					, 'FORM_BUILDER_TAB_DATA_SOURCE_INFO': "<?php echo __('The items you add to the listbox in this section will be data bound to the element. To make an item the default selection, select the item in the list and then click the \"Make default selection\" icon', 'booki') ?>"
					, 'FORM_BUILDER_TAB_DATAITEM_PLACEHOLDER': "<?php echo __('Data Item', 'booki') ?>"
					, 'FORM_BUILDER_TAB_FORM_ELEMENT_EMAIL_CAPABILITY_HEADING': "<?php echo __('Use this email field to auto register users', 'booki') ?>"
					, 'FORM_BUILDER_TAB_FORM_ELEMENT_EMAIL_CAPABILITY_INFO': "<?php echo __('These options allow you to provide some logic to email fields.', 'booki') ?>"
					, 'FORM_BUILDER_TAB_FORM_ELEMENT_NAME_CAPABILITY_HEADING': "<?php echo __('Use this as first name or last name fields', 'booki') ?>"
					, 'FORM_BUILDER_TAB_FORM_ELEMENT_NAME_CAPABILITY_INFO': "<?php echo __('If you\'ve disabled registration and just want to send user an email regarding their booking, the email will include this as either the customers first name or last name depending on selection below.', 'booki') ?>"
					, 'FORM_BUILDER_TAB_FORM_ELEMENT_CAPABILITY_NONE_LABEL': "<?php echo __('Just a regular textbox field', 'booki') ?>"
					, 'FORM_BUILDER_TAB_FORM_ELEMENT_CAPABILITY_REGISTER_THROUGH_EMAIL_LABEL': "<?php echo __('Use this email field to register the user. Registered users get first class treatment', 'booki') ?>"
					, 'FORM_BUILDER_TAB_FORM_ELEMENT_CAPABILITY_EMAIL_LABEL': "<?php echo __('Use this email field to send a one time notification to the user', 'booki') ?>"
					, 'FORM_BUILDER_TAB_FORM_ELEMENT_CAPABILITY_FIRSTNAME_LABEL': "<?php echo __('The value of this field is the first name or first name and last name', 'booki') ?>"
					, 'FORM_BUILDER_TAB_FORM_ELEMENT_CAPABILITY_LASTNAME_LABEL': "<?php echo __('The value of this field is the last name', 'booki') ?>"
					, 'FORM_BUILDER_TAB_FORM_ELEMENT_VALIDATION': "<?php echo __('Validation', 'booki') ?>"
					, 'FORM_BUILDER_TAB_FORM_ELEMENT_BASIC_CONSTRAINT': "<?php echo __('Basic constraints', 'booki') ?>"
					, 'FORM_BUILDER_TAB_DEFAULT_SELECTION': "<?php echo __('Default selection', 'booki') ?>"
					, 'FORM_BUILDER_TAB_DEFAULT_VALUE_PLACEHOLDER': "<?php echo __('Default value', 'booki') ?>"
					, 'FORM_BUILDER_TAB_DATASOURCE_ERROR_MSG': "<?php echo __('Your list cannot be empty. You need to add atleast 1 item.', 'booki') ?>"
					, 'FORM_BUILDER_TAB_ADD_VALUE': "<?php echo __('Add value', 'booki') ?>"
					, 'FORM_BUILDER_TAB_REMOVE_TITLE': "<?php echo __('Remove', 'booki') ?>"
					, 'FORM_BUILDER_TAB_MAKE_DEFAULT_SELECTION_TITLE': "<?php echo __('Make default selection', 'booki') ?>"
					, 'FORM_BUILDER_TAB_CONSTRAINT_HEADING': "<?php echo __('Validation - Advanced constraints', 'booki') ?>"
					, 'FORM_BUILDER_TAB_ALLOWED_VALUE_LABEL': "<?php echo __('Allowed value', 'booki') ?>"
					, 'FORM_BUILDER_TAB_ANY_VALUE_OPTION': "<?php echo __('Any value', 'booki') ?>"
					, 'FORM_BUILDER_TAB_ONLY_DIGITS_OPTION': "<?php echo __('Allow only digits from 0-9 (Negatives values not allowed.)', 'booki') ?>"
					, 'FORM_BUILDER_TAB_ONLY_NUMBERS_OPTION': "<?php echo __('Allow only numbers', 'booki') ?>"
					, 'FORM_BUILDER_TAB_ONLY_ALPHA_NUMERIC_OPTION': "<?php echo __('Allow only alphanumeric string', 'booki') ?>"
					, 'FORM_BUILDER_TAB_MIN_LENGTH_TITLE': "<?php echo __('Validates that the length of a string is at least as long as the given limit.', 'booki') ?>"
					, 'FORM_BUILDER_TAB_MIN_LENGTH_LABEL': "<?php echo __('Min length', 'booki') ?>"
					, 'FORM_BUILDER_TAB_MAX_LENGTH_TITLE': "<?php echo __('Validates that the length of a string is not larger than the given limit.', 'booki') ?>"
					, 'FORM_BUILDER_TAB_MAX_LENGTH_LABEL': "<?php echo __('Max length', 'booki') ?>"
					, 'FORM_BUILDER_TAB_MIN_TITLE': "<?php echo __('Validates given number is greater than this min number', 'booki') ?>"
					, 'FORM_BUILDER_TAB_MIN_LABEL': "<?php echo __('Min', 'booki') ?>"
					, 'FORM_BUILDER_TAB_MAX_TITLE': "<?php echo __('Validates given number is less than this max number.', 'booki') ?>"
					, 'FORM_BUILDER_TAB_MAX_LABEL': "<?php echo __('Max', 'booki') ?>"
					, 'FORM_BUILDER_TAB_REGEX_TITLE': "<?php echo __('Validates that a value matches a specific regular expression eg: validate a color hexadecimal code: [A-Fa-f0-9]{6}.', 'booki') ?>"
					, 'FORM_BUILDER_TAB_REGEX_LABEL': "<?php echo __('Regular expression (Regex)', 'booki') ?>"
					, 'FORM_BUILDER_TAB_NEW_RECORD_TITLE': "<?php echo __('New record', 'booki') ?>"
					, 'FORM_BUILDER_TAB_ADD_NEW_FORM_ELEMENT_TITLE': "<?php echo __('Add this new form element', 'booki') ?>"
					, 'FORM_BUILDER_TAB_MATCH_EMAIL_LABEL': "<?php echo __('Match an email', 'booki') ?>"
					, 'FORM_BUILDER_TAB_MATCH_URL_LABEL': "<?php echo __('Match a url', 'booki') ?>"
					, 'FORM_BUILDER_TAB_ADD_TITLE': "<?php echo __('Add', 'booki') ?>"
					, 'FORM_BUILDER_TAB_UPDATE_TITLE': "<?php echo __('Update', 'booki') ?>"
					, 'FORM_BUILDER_TAB_UPDATE_LABEL': "<?php echo __('Update', 'booki') ?>"
					, 'FORM_BUILDER_TAB_EDIT_FORM_ELEMENT_HEADING': "<?php echo __('Edit or delete an existing field', 'booki') ?>"
					, 'FORM_BUILDER_TAB_EDIT_FORM_ELEMENT_INFO': "<?php echo __('An overview of all the custom form fields created for this project.', 'booki') ?>"
					, 'FORM_BUILDER_TAB_QUICK_PREVIEW_LABEL': "<?php echo __('Quick preview', 'booki') ?>"
					, 'FORM_BUILDER_TAB_FORM_ELEMENT_ERROR_HEADING': "<?php echo __('Whoops!', 'booki') ?>"
					, 'FORM_BUILDER_TAB_FORM_ELEMENT_ERROR_INFO': "<?php echo __('Just hold it there Mister! You have not created any form elements yet.', 'booki') ?>"
					, 'FORM_BUILDER_TAB_FORM_ELEMENT_UNSAVED_CHANGES_INFO': "<?php echo __('You have unsaved changes. Save changes now ?', 'booki') ?>"
					, 'FORM_BUILDER_TAB_SAVE_LABEL': "<?php echo __('Save', 'booki') ?>"
					, 'FORM_BUILDER_TAB_EDIT_FIELD_TITLE': "<?php echo __('Edit field', 'booki') ?>"
					, 'FORM_BUILDER_TAB_DELETE_FIELD_TITLE': "<?php echo __('Delete field', 'booki') ?>"
					, 'FORM_BUILDER_TAB_DELETE_FIELD_HEADING': "<?php echo __('Delete Field', 'booki') ?>"
					, 'FORM_BUILDER_TAB_DELETE_FIELD_INFO': "<?php echo __('You are about to delete a field. Are you sure ?', 'booki') ?>"
					, 'FORM_BUILDER_TAB_QUICK_PREVIEW_HEADING': "<?php echo __('Quick preview', 'booki') ?>"
					, 'FORM_BUILDER_TAB_CREATE_FORM_FIELD_HEADING': "<?php echo __('Create form fields', 'booki') ?>"
					, 'FORM_BUILDER_TAB_ALL_FORM_FIELDS_LABEL': "<?php echo __('All form fields', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_HEADS_UP': "<?php echo __('Heads up', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_SAVE_DISCARD_CHANGES': "<?php echo __('You must save your changes or discard them to set \"Cost for special days\"?', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_BOOKING_DATE_RANGE_HEADING': "<?php echo __('Booking date range', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_BOOKING_DATE_RANGE_INFO': "<?php echo __('Specify the days you want to allow booking. Your users will be allowed to make bookings during a date period that falls within the following Start/End date.The cost is applied to each day within your selected period.', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_START_DATE_LABEL': "<?php echo __('Start date', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_END_DATE_LABEL': "<?php echo __('End date', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_BOOKING_START_LAPSE_HEADING': "<?php echo __('Booking start lapse', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_BOOKING_START_LAPSE_INFO': "<?php echo __('Booking is allowed only in advance of the number of days set below i.e. if you set 1 day, then bookings are allowed only 1 day before the current date. A value of 0 does not set this restriction and is the default.', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_BOOKING_START_LAPSE_LABEL': "<?php echo __('Booking allowed in advance of', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_BOOKING_LIMIT_HEADING': "<?php echo __('Available seats', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_BOOKING_LIMIT_INFO': "<?php echo __('This option limits bookings to the provided value. This is useful when you have a finite number of bookings eg: limited rooms for rent or seats in a bus etc. When the number of bookings is reached, bookings will close for this project. The value you see appened next to the textbox below is the number of bookings currently made in this project. A value of zero does not limit bookings and is the default.', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_SEAT_LABEL': "<?php echo __('Seats', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_DEPOSIT_LABEL': "<?php echo __('Deposits', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_MIN_DAYS_DEPOSIT_HEADING': "<?php echo __('Minimum number of days to deposit', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_MIN_DAYS_DEPOSIT_INFO': "<?php echo __('Booking starts from the first available date. If booking after the minimum number of days set below, then the deposit is required otherwise payment in full is required. The deposit value is a percentage value calculated from the total number of days.', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_MIN_DAYS_DEPOSIT_LABEL': "<?php echo __('Pay deposit if booking after', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_DAYS_LABEL': "<?php echo __('Days', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_DEPOSIT_HEADING': "<?php echo __('Deposit', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_DEPOSIT_INFO': "<?php echo __('The value you provide for deposit is percentage based which will be a percentage calculated from the overall cost of selected days. If the minimum days is provided, then the deposit is applicable if booking within the minimum days required above.', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_DEPOSIT_VALUE_LABEL': "<?php echo __('Deposit value', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_DISPLAY_COUNTER_INFO': "<?php echo __('Based on the available seats setting above, a counter is displayed in the page showing the number of available bookings left.', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_DISPLAY_COUNTER_LABEL': "<?php echo __('Display counter', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_EXCLUDE_RANGE_HEADING': "<?php echo __('Days to exclude from range', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_EXCLUDE_RANGE_INFO': "<?php echo __('Days to exclude from Date Range i.e. your day off, weekends etc', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_WEEK_DAYS_HEADING': "<?php echo __('Week days', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_EVERY_SUNDAY': "<?php echo __('Every Sunday', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_EVERY_MONDAY': "<?php echo __('Every Monday', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_EVERY_TUESDAY': "<?php echo __('Every Tuesday', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_EVERY_WEDNESDAY': "<?php echo __('Every Wednesday', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_EVERY_THURSDAY': "<?php echo __('Every Thursday', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_EVERY_FRIDAY': "<?php echo __('Every Friday', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_EVERY_SATURDAY': "<?php echo __('Every Saturday', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_BOOKABLE_DAYS_HEADING': "<?php echo __('Bookable days', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_COST_HEADING': "<?php echo __('Cost', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_COST_INFO': "<?php echo __('Applies the same cost to each day within selected period.', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_COST_ERROR': "<?php echo __('Value has to be a valid currency. Only 2 decimal places allowed.', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_DAY_OR_TIME_HEADING': "<?php echo __('Day vs time', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_DAY_OR_TIME_INFO_PART1': "<?php echo __('Day based booking applies cost to the entire day and users will be able to book an entire day at a time.', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_DAY_OR_TIME_INFO_PART2': "<?php echo __('Time based booking splits a day in equal time intervals based on the HH:MM selected. Users will be able to book for a certain time interval within a day. ', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_DAY_BASED': "<?php echo __('Day based', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_TIME_BASED': "<?php echo __('Time based', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_TIME_HEADING': "<?php echo __('Time', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_TIME_INFO': "<?php echo __('The time selected will be split into equal intervals i.e. selecting 01:00 will give you bookable time slots split evenly starting from 12:00am - 1:00am, 1:00am - 2:00am, 2:00am - 3:00am and so forth. Likewise, selecting 23:60 ( a 24 hour duration) will generate only a single timeslot where the user will be making bookings by the day instead of by day and time.', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_HOUR_LABEL': "<?php echo __('Hour', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_MINUTE_LABEL': "<?php echo __('Minute', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_ENABLE_SINGLE_HOUR_MINUTE_FORMAT_HEADING': "<?php echo __('Enables single hour:minute format', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_ENABLE_SINGLE_HOUR_MINUTE_FORMAT_INFO': "<?php echo __('When checked single hour:minute format will be used for the time slots. Otherwise, defaults to range format eg: hour:minute - hour:minute.', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_ENABLE_SINGLE_HOUR_MINUTE_FORMAT_LABEL': "<?php echo __('Enable single hour:minute format', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_TIME_INTERVAL_HEADING': "<?php echo __('Split interval start time', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_TIME_INTERVAL_INFO': "<?php echo __('When time slots are split, they will start the split at the following hour and minute interval selected. For example, if you selected 10:15, i.e. Hour:10 and minute:15, then the time slots split will begin at 10:15 and split time evenly for the entire day starting with 10:15. This allows you more accuracy. By default, the split will start from 00:00.', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_HOUR_START_INTERVAL_LABEL': "<?php echo __('Hour interval start', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_MINUTE_START_INTERVAL_LABEL': "<?php echo __('Minute interval start', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_BOOKABLE_TIME_SLOTS_LABEL': "<?php echo __('Bookable time slots', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_RESET_TIMESLOT_LABEL': "<?php echo __('Reset timeslot', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_UPDATE_LABEL': "<?php echo __('Update', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_CREATE_LABEL':  "<?php echo __('Create', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_DISCARD_CHANGES_LABEL': "<?php echo __('Discard changes', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_BOOKING_PERIOD_LABEL': "<?php echo __('Booking Period', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_COST_PER_DAY_LABEL': "<?php echo __('Special days', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_COST_PER_DAY_HEADING': "<?php echo __('Specify cost for special days', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_COST_PER_DAY_INFO': "<?php echo __('Set costs for special days if your costs differ by day, i.e. season.', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_SELECTED_DAYS_LIST_LABEL': "<?php echo __('List of days within selected season', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_SELECTION_MODE_LABEL': "<?php echo __('Select dates by', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_CREATE_NEW_SEASON': "<?php echo __('Create new season', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_ADD_SEASON': "<?php echo __('Add season', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_SEASON': "<?php echo __('Season', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_SEASON_NAME_LABEL': "<?php echo __('Season name', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_NAMELESS_SEASON_INFO': "<?php echo __('You have un-named seasons which are no longer supported and will be deprecated soon.', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_UNNAMED_SEASON': "<?php echo __('Un-named', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_NAMELESS_SEASON_LABEL': "<?php echo __('Delete un-named', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_EXCLUDE_RANGE_HEADING': "<?php echo __('Days to exclude from list of days in selected season', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_EXCLUDE_RANGE_INFO': "<?php echo __('Days to exclude by week day from list of days above. For example, if you want only mondays to be included in the list above, then select every other weekday below. If a weekday is checked below, this means either the weekday is excluded or the weekday is not available in the selected range and will not appear in the list of days above.', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_WEEK_DAYS_HEADING': "<?php echo __('Week days', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_DELETE_SEASON_LABEL': "<?php echo __('Delete season', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_UPDATE_SEASON_LABEL': "<?php echo __('Update season', 'booki') ?>"
					, 'BOOKING_PERIOD_TAB_WEEK_DAY_COUNT': "<?php echo __('No. of days for weekday found in selected date range.', 'booki') ?>"
					, 'OPTIONALS_TAB_HEADING': "<?php echo __('Specify extra billable items', 'booki') ?>"
					, 'OPTIONALS_TAB_INFO': "<?php echo __('Bookings can allow extra billable items. These are displayed as a list of checkboxes and are an integral part of the booking process. ', 'booki') ?>"
					, 'OPTIONALS_TAB_ITEM_NAME_LABEL': "<?php echo __('Optional Item Name', 'booki') ?>"
					, 'OPTIONALS_TAB_COST_LABEL': "<?php echo __('Cost', 'booki') ?>"
					, 'OPTIONALS_TAB_COST_ERROR': "<?php echo __('Value has to be a valid currency. Only 2 decimal places allowed.', 'booki') ?>"
					, 'OPTIONALS_TAB_NEW_INFO': "<?php echo __('New record', 'booki') ?>"
					, 'OPTIONALS_TAB_ADD_NEW_INFO': "<?php echo __('Add new optional', 'booki') ?>"
					, 'OPTIONALS_TAB_UPDATE_LABEL': "<?php echo __('Update', 'booki') ?>"
					, 'OPTIONALS_TAB_DELETE_LABEL': "<?php echo __('Delete', 'booki') ?>"
					, 'CASCADING_LIST_TAB_DATASOURCE_HEADING': "<?php echo __('Data source', 'booki') ?>"
					, 'CASCADING_LIST_TAB_DATASOURCE_INFO': "<?php echo __('The items you add to the listbox in this section below are the items that will show in your dropdownlist selected above. Note: don\'t set cost if cost does not apply. Costs of 0.00 will be ignored.', 'booki') ?>"
					, 'CASCADING_LIST_TAB_DATAITEM_PLACEHOLDER': "<?php echo __('Data Item', 'booki') ?>"
					, 'CASCADING_LIST_TAB_DATASOURCE_ERROR_MSG': "<?php echo __('Your list cannot be empty. You need to add atleast 1 item.', 'booki') ?>"
					, 'CASCADING_LIST_TAB_REFRESH_LABEL': "<?php echo __('New item', 'booki') ?>"
					, 'CASCADING_LIST_TAB_ADD_VALUE_LABEL': "<?php echo __('Add value', 'booki') ?>"
					, 'CASCADING_LIST_TAB_REMOVE_LABEL': "<?php echo __('Remove', 'booki') ?>"
					, 'CASCADING_LIST_TAB_VALUE_LABEL': "<?php echo __('Value', 'booki') ?>"
					, 'CASCADING_LIST_TAB_LABEL_LABEL': "<?php echo __('Label', 'booki') ?>"
					, 'CASCADING_LIST_SELECT_LABEL': "<?php echo __('Select Cascading List', 'booki') ?>"
					, 'CASCADING_LIST_CREATE_NEW_LABEL': "<?php echo __('Create new', 'booki') ?>"
					, 'CASCADING_LIST_CREATE_BUTTON_LABEL': "<?php echo __('Create', 'booki') ?>"
					, 'CASCADING_LIST_UPDATE_BUTTON_LABEL': "<?php echo __('Update', 'booki') ?>"
					, 'CASCADING_LIST_DELETE_HEADING': "<?php echo __('Delete List', 'booki') ?>"
					, 'CASCADING_LIST_DELETE_INFO': "<?php echo __('You are about to delete a list. You will also lose any cascading items related to this list. Are you sure ?', 'booki') ?>"
					, "CASCADING_LIST_CLOSE_BUTTON_LABEL": "<?php echo __('Close', 'booki') ?>"
					, 'CASCADING_LIST_DELETE_BUTTON_LABEL': "<?php echo __('Delete', 'booki') ?>"
					, 'CASCADING_LIST_COST_LABEL': "<?php echo __('Cost', 'booki') ?>"
					, 'CASCADING_LIST_COST_ERROR': "<?php echo __('Value has to be a valid currency. Only 2 decimal places allowed', 'booki') ?>"
					, 'CASCADING_LIST_ITEM_LABEL': "<?php echo __('Dropdown list items', 'booki') ?>"
					, 'CASCADING_LIST_SELECT_RELATION_PARENT_LABEL': "<?php echo __('Select the parent list', 'booki') ?>"
					, 'CASCADING_LIST_ITEM_RELATION_HEADING': "<?php echo __('Cascading list relationships', 'booki') ?>"
					, 'CASCADING_LIST_ITEM_RELATION_INFO': "<?php echo __('Use this section only after having created atleast 2 lists. This is where you set up relationships for the cascade. Select an item in the list above. Then select a list below and click the update button. Everytime the item from the list above is selected, the items from the list below will be loaded. Confused ? Me too!', 'booki') ?>"
					, 'CASCADING_LIST_SELECT_RELATION_LABEL': "<?php echo __('Select a relationship', 'booki') ?>"
					, 'CASCADING_LIST_IS_REQUIRED_INFO': "<?php echo __('Is required (user needs to make a selection)', 'booki') ?>"
					, 'CASCADING_LIST_HEADING': "<?php echo __('Auto loading Cascading Drop Down Lists', 'booki') ?>"
					, 'CASCADING_LIST_INFO': "<?php echo __('Each list created will appear in your front end as a regular dropdown list. You can also create auto loading cascading lists. Cascading lists will auto populate a secondary list when an element in one list is selected. Note: For cascading lists you need to define at least 2 lists where one item in either of lists is related to the other. Confused ? Me too!', 'booki') ?>"
				};
			});
		</script>
		<div class="booki-content-box">
			<?php 
				echo str_replace('[image-gallery]', $_Booki_Create->imageListContent, file_get_contents(dirname(__FILE__) . '/static/steps.html'));
			?>
		</div>
	</div>
</div>